c.logo = function() {
    push(),
    rectMode(CENTER),
    push(),
    translate(width / 2, height / 2),
    noStroke(),
    rotate("menu trans" === Bt.screen ? -s.theta : 0),
    rectMode(CENTER),
    fill(255),
    rect(0, 0, 5 * s.cross, height * s.cross),
    rotate(-s.theta),
    pop(),
    push(),
    translate(width / 2, height / 2),
    translate((width < height ? width : height) / 500 * 5, (width < height ? width : height) / 500 * 5),
    fill(0, 100),
    noStroke(),
    rotate(s.theta),
    rect(0, 0, s.w * s.pulse * ((width < height ? width : height) / 3) + .05 * s.size * ((width < height ? width : height) / 3), s.h * s.pulse * ((width < height ? width : height) / 3) + .05 * s.size * ((width < height ? width : height) / 3)),
    pop(),
    push(),
    translate(width / 2, height / 2),
    rotate(s.theta),
    fill(s.fillC[0], s.fillC[1] / 175 * 125, s.fillC[2] / 255 * 205, s.fillC[3]),
    strokeWeight(.05 * s.size * ((width < height ? width : height) / 3)),
    stroke(s.strC[0], s.strC[1], s.strC[2], s.strC[3]),
    rect(0, 0, s.w * s.pulse * ((width < height ? width : height) / 3), s.h * s.pulse * ((width < height ? width : height) / 3)),
    pop(),
    push(),
    translate(width / 2, height / 2),
    translate((width < height ? width : height) / 500 * 5, (width < height ? width : height) / 500 * 5),
    fill(0, 100),
    noStroke(),
    rotate(s.theta),
    rotate(22.5),
    rect(0, 0, s.w * (s.pulse / 3 * 2 + 1 / 3) * ((width < height ? width : height) / 3) + .05 * s.size * ((width < height ? width : height) / 3), s.h * (s.pulse / 3 * 2 + 1 / 3) * ((width < height ? width : height) / 3) + .05 * s.size * ((width < height ? width : height) / 3)),
    pop(),
    push(),
    translate(width / 2, height / 2),
    rotate(s.theta),
    rotate(22.5),
    fill(s.fillC[0], s.fillC[1], s.fillC[2], s.fillC[3]),
    srokeWeight(.05 * s.size * ((width < height ? width : height) / 3)),
    stroke(s.strC[0], s.strC[1], s.strC[2], s.strC[3]),
    rect(0, 0, s.w * (s.pulse / 3 * 2 + 1 / 3) * ((width < height ? width : height) / 3), s.h * (s.pulse / 3 * 2 + 1 / 3) * ((width < height ? width : height) / 3)),
    noStroke(),
    rotate(-22.5),
    rotate(-s.theta),
    textStyle(BOLD),
    $e = "",
    textAlign(CENTER, CENTER),
    textSize(s.size * (s.pulse / 3 + 2 / 3) / 500 * 250 * ((width < height ? width : height) / 3)),
    fill(0, s.strC[3] / 255 * 100),
    text("Pulsehax", 0 + (width < height ? width : height) / 500 * 5, 0 + (width < height ? width : height) / 500 * 5),
    fill(s.strC[0], s.strC[1], s.strC[2], s.strC[3]),
    text("Pulsehax", 0, 0),
    (push(),
    scale(s.size * (s.pulse / 3 + 2 / 3)),
    textSize((width < height ? width : height) / 3 * .5 / 5),
    fill(0, s.strC[3] / 255 * 100),
    text("Unofficial Client", 4 * -kt + (width < height ? width : height) / 500 * 1.15, 3 * kt + (width < height ? width : height) / 500 * 1.15),
    fill(s.strC[0], s.strC[1], s.strC[2], s.strC[3]),
    text("Unofficial Client", 4 * -kt, 3 * kt),
    pop()),
    !0 === Xe.active && (fill(255, 0, 0, s.strC[3]),
    text("ADMIN", 0, height / 4)),
    pop(),
    pop(),
    fill(s.strC[0], s.strC[1], s.strC[2], s.strC[3]),
    textAlign(CENTER, BOTTOM),
    textSize(kt),
    text("Access the Pulsehax menu and Developer console in settings!", width / 2, height - kt),
    Kt(width - 7 * kt, height - 7 * kt * (s.strC[3] / 255), 6 * kt, 6 * kt, "", Bt.account.buttonHover, 19, {
        discord: !0
    })
};

function Cs() {
    background(255);
    var e = width > height ? width / 64 : height / 64
        , t = (fill(0, s.textA),
    textSize(100),
    textAlign(CENTER, CENTER),
    Pt("welcome", xt) + (1 === s.wave ? " o/" : ""))
        , i = (fill(0, 0),
    Dt(t, width / 2, height / 2, width / 4, height / 4),
    split(t, ""));
    textAlign(LEFT, CENTER),
    textSize(5 * e),
    noStroke();
    for (var o, n = 0; n < i.length; n++)
        void 0 !== Ze[n] ? (push(),
        translate(0, 8 * e * Ze[n]),
        fill(0, 255 - 255 * (abs(Ze[n]) < .25 ? 4 * abs(Ze[n]) : 1)),
        o = textWidth(t.substr(0, n)),
        text(i[n], width / 2 + o - textWidth(t) / 2, height / 2),
        s.drop ? Ze[n] += At(pow(-1, n), Ze[n], .15 * Ze.length / 7 * (n < Ze.length - 1 ? abs(Ze[n + 1]) : 1)) : Ze[n] += At(0, Ze[n], (.075 - .03 * n / i.length) * (0 < n ? abs(abs(Ze[n - 1]) - 1) : 1)),
        pop()) : Ze[n] = pow(-1, n);
    !1 === s.drop && (rectMode(CORNER),
    fill(190),
    rect(0, 0 - height / 2 * (1 - abs(Ze[3])) * 1, width, height / 2),
    rect(0, height / 2 + height / 2 * (1 - abs(Ze[3])) * 1, width, height / 2),
    fill(130),
    rect(0, 0 - height / 2 * (1 - abs(Ze[2])) * 1, width, height / 2),
    rect(0, height / 2 + height / 2 * (1 - abs(Ze[2])) * 1, width, height / 2),
    fill(70),
    rect(0, 0 - height / 2 * (1 - abs(Ze[1])) * 1, width, height / 2),
    rect(0, height / 2 + height / 2 * (1 - abs(Ze[1])) * 1, width, height / 2),
    fill(10),
    rect(0, 0 - height / 2 * (1 - abs(Ze[0])) * 1, width, height / 2),
    rect(0, height / 2 + height / 2 * (1 - abs(Ze[0])) * 1, width, height / 2),
    fill(255),
    textAlign(CENTER, CENTER),
    Dt(Pt("clickToPlay", xt), width / 2, height - height / 8 + height / 2 * (1 - abs(Ze[0])) * 1, width, height / 32),
    5e3 <= millis() - s.startTime) && (s.drop = !0,
    s.dropTime = millis()),
    !1 === s.drop ? s.textA += At(255, s.textA, .1) : (s.textA += At(0, s.textA, .1),
    push(),
    rectMode(CENTER),
    translate(width / 2, s.boxY),
    noStroke(),
    rotate("menu trans" === Bt.screen ? -s.theta : 0),
    rectMode(CENTER),
    fill(255),
    rect(0, 0, 5 * s.cross, height * s.cross),
    rotate(-s.theta),
    fill(s.fillC[0], s.fillC[1] / 175 * 125, s.fillC[2] / 255 * 205, s.fillC[3]),
    strokeWeight(.05 * s.size * ((width < height ? width : height) / 3)),
    stroke(s.strC[0], s.strC[1], s.strC[2], s.strC[3]),
    rect(0, 0, s.size * ((width < height ? width : height) / 3), s.size * ((width < height ? width : height) / 3)),
    rotate(22.5 * s.size),
    fill(s.fillC[0], s.fillC[1], s.fillC[2], s.fillC[3]),
    strokeWeight(.05 * s.size * ((width < height ? width : height) / 3)),
    stroke(s.strC[0], s.strC[1], s.strC[2], s.strC[3]),
    rect(0, 0, s.size * ((width < height ? width : height) / 3), s.size * ((width < height ? width : height) / 3)),
    noStroke(),
    rotate(-22.5 * s.size),
    rotate(s.theta),
    textStyle(BOLD),
    $e = "",
    textAlign(CENTER, CENTER),
    textSize(+s.size / 500 * 250 * ((width < height ? width : height) / 3)),
    fill(0, s.strC[3] / 255 * 100),
    text("Pulsehax", 0 + (width < height ? width : height) / 500 * 5, 0 + (width < height ? width : height) / 500 * 5),
    fill(s.strC[0], s.strC[1], s.strC[2], s.strC[3]),
    text("Pulsehax", 0, 0),
    (push(),
    scale(+s.size),
    textSize((width < height ? width : height) / 3 * .5 / 5),
    fill(0, s.strC[3] / 255 * 100),
    text("Unnoficial Client", 4 * -e + (width < height ? width : height) / 500 * 1.15, 3 * e + (width < height ? width : height) / 500 * 1.15),
    fill(s.strC[0], s.strC[1], s.strC[2], s.strC[3]),
    text("Unnoficial Client", 4 * -e, 3 * e),
    pop()),
    !0 === Xe.active && (fill(255, 0, 0, s.strC[3]),
    text("ADMIN", 0, height / 4)),
    pop(),
    millis() < s.dropTime + 1e3 ? (s.boxY = Bi(millis() - s.dropTime, millis() - s.dropTime, 0, height / 2, 999),
    s.size = fi(millis() - s.dropTime, millis() - s.dropTime, 100, 250, 999) / 350,
    s.theta = fi(millis() - s.dropTime, millis() - s.dropTime, 0, -540, 999),
    s.fillC[0] = vi(millis() - s.dropTime, millis() - s.dropTime, 0, 0, 999),
    s.fillC[1] = vi(millis() - s.dropTime, millis() - s.dropTime, 0, 175, 999),
    s.fillC[2] = vi(millis() - s.dropTime, millis() - s.dropTime, 0, 255, 999),
    s.fillC[3] = vi(millis() - s.dropTime, millis() - s.dropTime, 255, 0, 999),
    s.strC[0] = vi(millis() - s.dropTime, millis() - s.dropTime, 0, 255, 999),
    s.strC[1] = vi(millis() - s.dropTime, millis() - s.dropTime, 0, 255, 999),
    s.strC[2] = vi(millis() - s.dropTime, millis() - s.dropTime, 0, 255, 999),
    s.strC[3] = vi(millis() - s.dropTime, millis() - s.dropTime, 255, 0, 999)) : (s.fillC[0] = 0,
    s.fillC[1] = 175,
    s.fillC[2] = 255,
    s.fillC[3] = 255,
    s.strC[0] = 255,
    s.strC[1] = 255,
    s.strC[2] = 255,
    s.strC[3] = 255,
    s.boxY = height / 2,
    s.size = 1,
    s.w = s.size,
    s.h = s.size,
    to(),
    He = "menu"))
}